name: Build Windows x64 RustDesk

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.22.3"
  LLVM_VERSION: "15.0.6"
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "1.4.1-custom"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  generate-bridge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install prerequisites
        run: |
          sudo apt-get install ca-certificates -y
          sudo apt-get update -y
          sudo apt-get install -y \
            clang \
            cmake \
            curl \
            gcc \
            git \
            g++ \
            libclang-dev \
            libgtk-3-dev \
            llvm-dev \
            nasm \
            ninja-build \
            pkg-config \
            wget

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-unknown-linux-gnu
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: bridge-ubuntu-22.04

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          cargo install cargo-expand --version 1.0.95 --locked
          cargo install flutter_rust_bridge_codegen --version 1.80.1 --features "uuid" --locked
          pushd flutter && sed -i -e 's/extended_text: 14.0.0/extended_text: 13.0.0/g' pubspec.yaml && flutter pub get && popd

      - name: Run flutter rust bridge
        run: |
          ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/macos/Runner/bridge_generated.h
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: bridge-artifact
          path: |
            ./src/bridge_generated.rs
            ./src/bridge_generated.io.rs
            ./flutter/lib/generated_bridge.dart
            ./flutter/lib/generated_bridge.freezed.dart
            ./flutter/macos/Runner/bridge_generated.h
            ./flutter/ios/Runner/bridge_generated.h

  build-windows-x64:
    name: Build Windows x64
    needs: [generate-bridge]
    runs-on: windows-2022
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Replace engine with rustdesk custom flutter engine
        run: |
          flutter doctor -v
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive -Path windows-x64-release.zip -DestinationPath windows-x64-release
          Move-Item -Path "windows-x64-release\*" -Destination "C:\hostedtoolcache\windows\flutter\stable-${{ env.FLUTTER_VERSION }}-x64\bin\cache\artifacts\engine\windows-x64-release\" -Force

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: windows-2022

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          if (!(& "$env:VCPKG_ROOT\vcpkg.exe" install --triplet x64-windows-static --x-install-root="$env:VCPKG_ROOT\installed")) {
            Get-ChildItem -Path "$env:VCPKG_ROOT" -Recurse -Filter "*.log" | ForEach-Object {
              Write-Host "$($_.FullName):"
              Write-Host "======"
              Get-Content $_.FullName
              Write-Host "======"
              Write-Host ""
            }
            exit 1
          }
          Get-Content "$env:VCPKG_ROOT\buildtrees\ffmpeg\build-x64-windows-static-rel-out.log" -Head 100 -ErrorAction SilentlyContinue

      - name: Build rustdesk
        run: |
          # Windows: build RustDesk
          Write-Host "Starting RustDesk build..."
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          
          # Check if flutter build directory exists
          Write-Host "Checking flutter build directory..."
          if (Test-Path ".\flutter\build\windows\x64\runner\Release") {
            Write-Host "Flutter build directory found"
            Move-Item -Path ".\flutter\build\windows\x64\runner\Release" -Destination ".\rustdesk"
          } else {
            Write-Host "Flutter build directory not found. Checking flutter directory structure..."
            Get-ChildItem -Path ".\flutter\build" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
            Write-Host "Flutter build failed. Exiting."
            exit 1
          }

          # Download usbmmidd_v2.zip and extract it to ./rustdesk
          Invoke-WebRequest -Uri https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip -OutFile usbmmidd_v2.zip
          Expand-Archive usbmmidd_v2.zip -DestinationPath .
          Remove-Item -Path "usbmmidd_v2\Win32" -Recurse
          Remove-Item -Path "usbmmidd_v2\deviceinstaller64.exe", "usbmmidd_v2\deviceinstaller.exe", "usbmmidd_v2\usbmmidd.bat"
          Move-Item -Path ".\usbmmidd_v2" -Destination ".\rustdesk" -Force

      - name: Upload RustDesk.exe
        uses: actions/upload-artifact@master
        with:
          name: RustDesk-Windows-x64
          path: rustdesk/rustdesk.exe

      - name: Create release package
        run: |
          # Create a zip file with the executable
          Compress-Archive -Path ./rustdesk/* -DestinationPath ./RustDesk-Windows-x64-${{ env.VERSION }}.zip

      - name: Upload release package
        uses: actions/upload-artifact@master
        with:
          name: RustDesk-Windows-x64-Package
          path: RustDesk-Windows-x64-${{ env.VERSION }}.zip

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: RustDesk Custom v${{ env.VERSION }}
          body: |
            ## RustDesk Custom Build
            
            This is a custom build of RustDesk with additional command line parameters:
            
            - `--fullscreen=true/false`: Set fullscreen or window mode
            - `--collapse_toolbar=true/false`: Hide or show toolbar by default
            - `--desktop_scaling=true/false`: Scale desktop to fit window or keep original size
            
            ### Changes from original RustDesk:
            - Added support for command line parameters to control UI behavior
            - Enhanced remote desktop experience with customizable settings
            
            ### Usage Examples:
            ```
            # Start in fullscreen mode with hidden toolbar
            rustdesk.exe --fullscreen=true --collapse_toolbar=true
            
            # Start in window mode with desktop scaling
            rustdesk.exe --fullscreen=false --desktop_scaling=true
            ```
          files: |
            RustDesk-Windows-x64-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
