name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - 'flutter/**'
      - '.github/workflows/**'

jobs:
  test-build:
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "1.75"
          targets: x86_64-pc-windows-msvc

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.5"

      - name: Verify Flutter
        run: |
          flutter --version
          flutter doctor -v

      - name: Test Rust compilation
        run: |
          cargo check --features flutter

      - name: Test Flutter compilation
        run: |
          cd flutter
          flutter clean
          flutter pub get
          flutter analyze
